export const LIST_ALL_EXPENSES = "LIST_ALL_EXPENSES";
export const ADD_EXPENSE = "ADD_EXPENSE";
export const FILTER_EXPENSES = "FILTER_EXPENSES";
export const REMOVE_EXPENSE = "REMOVE_EXPENSE";
export const CHANGE_LANG = "CHANGE_LANG";

const USER_LOGGED_IN = "USER_LOGGED_IN";
const USER_LOGGED_OUT = "USER_LOGGED_OUT";
const FILTER_UPDATE = "FILTER_UPDATE";

const EXPENSE_DELETED = "EXPENSE_DELETED";
const EXPENSE_ADDED = "EXPENSE_ADDED";
const GET_EXPENSES_LIST = "GET_EXPENSES_LIST";

export {
  USER_LOGGED_IN,
  USER_LOGGED_OUT,
  FILTER_UPDATE,
  EXPENSE_DELETED,
  EXPENSE_ADDED,
  GET_EXPENSES_LIST,
};
