export const LIST_ALL_EXPENSES = 'LIST_ALL_EXPENSES'
export const ADD_EXPENSE = "ADD_EXPENSE";
export const FILTER_EXPENSES = "FILTER_EXPENSES";
export const REMOVE_EXPENSE = "REMOVE_EXPENSE";
export const CHANGE_LANG = "CHANGE_LANG";